### ISSUE TITLE
NVCC not Found

### ISSUE THREAD

**Issue by abdksyed** [rlan/notebooks#111]
I am trying to install detectron2, after building pytorch1.12.1 docker image with gpu.

But it is giving an error nvcc not found.

**Comment by rlan** [comment]
@abdksyed Thank you for reporting an issue. My images are built from Nvidia's official runtime-flavored images, e.g. nvidia/cuda:11.6.2-cudnn8-runtime-ubuntu20.04. This is documented in the container's description field (via docker inspect command) and in its Dockerfile. Runtime-flavored images apparently does not include NVCC.If NVCC is needed, I recommend that you build a new image based on devel-flavored instead. Ref: https://github.com/NVIDIA/nvidia-docker/issues/1160#issuecomment-568814500
